name: Build and Publish DLLs

on:
  repository_dispatch:
    types: [build-dlls]

jobs:
  build_and_publish:
    runs-on: windows-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.triggered_commit }}

      - name: Extract version digits from tag
        id: extract_version
        run: |
          $TAG="${{ github.event.client_payload.commit_tag }}"
          if (-not ($TAG -match '^v\d+\.\d+\.\d+.*?$')) {
            echo "Invalid tag format: $TAG"
            exit 1
          }
          $version=$TAG.Substring(1)
          echo "VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          $repositoryFullName = ${{ github.event.client_payload.repository }}
          $repositoryName = ($repositoryFullName -split '/')[1]
          echo "REPO_NAME=$repositoryName" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Restore NuGet packages
        run: |
            dotnet nuget add source --username HolidayMan --password ${{ secrets.GH_PAT_PACK }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.event.client_payload.repo_owner }}/index.json"
            dotnet restore .\${{ env.REPO_NAME }}\${{ env.REPO_NAME }}.csproj

      - name: Build DLLs
        run: dotnet build -c Release

      - name: Pack NuGet package
        run: dotnet pack .\${{ env.REPO_NAME }}\${{ env.REPO_NAME }}.csproj -c Release /p:PackageVersion=${{ env.VERSION }}

      - name: Publish DLLs to GitHub Packages
        run: dotnet nuget push D:\a\${{ env.REPO_NAME }}\${{ env.REPO_NAME }}\${{ env.REPO_NAME }}\bin\Release\${{ env.REPO_NAME }}.${{ env.VERSION }}.nupkg --source "https://nuget.pkg.github.com/${{ github.event.client_payload.repo_owner }}/index.json" --api-key ${{ secrets.GH_PAT_PACK }}
